using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace RoadGen.Core;

/// <summary>Reconstructs road control points from a VMF file that contains
/// displacement solids (e.g. files generated by RoadGen or Twister).</summary>
public static class VmfImporter
{
    /// <summary>Extracts a list of road control points (position + width) from the
    /// displacement surfaces found in the VMF text.</summary>
    public static List<RoadPoint> ImportRoad(string vmfText)
    {
        VmfBlock root = VmfParser.Parse(vmfText);
        VmfBlock world = root.Children.FirstOrDefault(b => b.Name.Equals("world", StringComparison.OrdinalIgnoreCase))
            ?? throw new InvalidOperationException("No 'world' block found in the VMF.");

        var samples = new List<(Vec3 center, double width, Vec3 across)>();

        foreach (VmfBlock solid in world.Children)
        {
            if (!solid.Name.Equals("solid", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            foreach (VmfBlock side in solid.Children)
            {
                if (!side.Name.Equals("side", StringComparison.OrdinalIgnoreCase))
                {
                    continue;
                }

                VmfBlock disp = side.Children.FirstOrDefault(b => b.Name.Equals("dispinfo", StringComparison.OrdinalIgnoreCase));
                if (disp == null)
                {
                    continue;
                }

                Vec3[,] grid = Reconstruct(side, disp);
                int res = grid.GetLength(0) - 1;

                // One sample at each end of the segment (adjacent segments share
                // their end rows, so duplicates are removed afterwards).
                samples.Add(Endpoint(grid, 0, res));
                samples.Add(Endpoint(grid, res, res));

                // A solid has at most one displacement face.
                break;
            }
        }

        if (samples.Count < 2)
        {
            throw new InvalidOperationException("No displacement surfaces found in the VMF.");
        }

        // Drop samples shared between adjacent segments.
        var deduped = new List<(Vec3 center, double width, Vec3 across)>();
        foreach (var s in samples)
        {
            if (deduped.Count > 0 && (deduped[deduped.Count - 1].center - s.center).Length < 0.5)
            {
                continue;
            }

            deduped.Add(s);
        }

        var points = new List<RoadPoint>();
        for (int i = 0; i < deduped.Count; i++)
        {
            Vec3 prev = i > 0 ? deduped[i - 1].center : deduped[i].center;
            Vec3 next = i < deduped.Count - 1 ? deduped[i + 1].center : deduped[i].center;
            double bank = EstimateBank(prev, deduped[i].center, next, deduped[i].across);
            points.Add(new RoadPoint(deduped[i].center, deduped[i].width, bank));
        }

        return points;
    }

    private static (Vec3 center, double width, Vec3 across) Endpoint(Vec3[,] grid, int row, int res)
    {
        Vec3 left = grid[row, 0];
        Vec3 right = grid[row, res];
        Vec3 across = (right - left).Normalized();
        return ((left + right) / 2.0, (right - left).Length, across);
    }

    /// <summary>Recovers the bank (roll) angle from the tilt of the road cross-section.
    /// Bank is not stored in a VMF, but it is encoded in the surface geometry.</summary>
    private static double EstimateBank(Vec3 prev, Vec3 current, Vec3 next, Vec3 across)
    {
        Vec3 travel = next - prev;
        if (travel.LengthSq < 1e-9)
        {
            return 0;
        }

        Vec3 t = travel.Normalized();
        Vec3 roadUp = Vec3.Cross(across, t).Normalized();
        Vec3 levelUp = (Vec3.UnitZ - t * Vec3.Dot(Vec3.UnitZ, t)).Normalized();

        double angle = Math.Atan2(Vec3.Dot(Vec3.Cross(levelUp, roadUp), t), Vec3.Dot(levelUp, roadUp));
        return angle * 180.0 / Math.PI;
    }

    private static Vec3[,] Reconstruct(VmfBlock side, VmfBlock disp)
    {
        if (!side.Properties.TryGetValue("plane", out string planeStr))
        {
            throw new InvalidOperationException("A displacement side is missing its plane.");
        }

        Vec3[] corners = ParsePlane(planeStr);
        Vec3 A = corners[0];
        Vec3 B = corners[1];
        Vec3 C = corners[2];

        if (!disp.Properties.TryGetValue("power", out string powerStr))
        {
            throw new InvalidOperationException("A dispinfo block is missing its power.");
        }

        int power = int.Parse(powerStr, CultureInfo.InvariantCulture);
        int res = 1 << power;
        int n = res + 1;

        Vec3[,] normals = ParseVectorGrid(disp, "normals", n);
        double[,] distances = ParseScalarGrid(disp, "distances", n);

        // Rebuild each surface vertex: base + normal * distance. The base face is
        // the parallelogram spanned by (B - A) along rows and (C - B) along columns.
        Vec3[,] grid = new Vec3[n, n];
        for (int r = 0; r < n; r++)
        {
            for (int c = 0; c < n; c++)
            {
                Vec3 basePoint = A + (B - A) * (r / (double)res) + (C - B) * (c / (double)res);
                grid[r, c] = basePoint + normals[r, c] * distances[r, c];
            }
        }

        return grid;
    }

    private static Vec3[] ParsePlane(string s)
    {
        List<double> nums = ParseNumbers(s);
        if (nums.Count < 9)
        {
            throw new InvalidOperationException("Invalid plane string: " + s);
        }

        return new[]
        {
            new Vec3(nums[0], nums[1], nums[2]),
            new Vec3(nums[3], nums[4], nums[5]),
            new Vec3(nums[6], nums[7], nums[8])
        };
    }

    private static Vec3[,] ParseVectorGrid(VmfBlock disp, string blockName, int n)
    {
        var result = new Vec3[n, n];
        VmfBlock block = disp.Children.FirstOrDefault(b => b.Name.Equals(blockName, StringComparison.OrdinalIgnoreCase));
        if (block == null)
        {
            return result;
        }

        for (int r = 0; r < n; r++)
        {
            if (block.Properties.TryGetValue("row" + r, out string line))
            {
                List<double> nums = ParseNumbers(line);
                for (int c = 0; c < n && c * 3 + 2 < nums.Count; c++)
                {
                    result[r, c] = new Vec3(nums[c * 3], nums[c * 3 + 1], nums[c * 3 + 2]);
                }
            }
        }

        return result;
    }

    private static double[,] ParseScalarGrid(VmfBlock disp, string blockName, int n)
    {
        var result = new double[n, n];
        VmfBlock block = disp.Children.FirstOrDefault(b => b.Name.Equals(blockName, StringComparison.OrdinalIgnoreCase));
        if (block == null)
        {
            return result;
        }

        for (int r = 0; r < n; r++)
        {
            if (block.Properties.TryGetValue("row" + r, out string line))
            {
                List<double> nums = ParseNumbers(line);
                for (int c = 0; c < n && c < nums.Count; c++)
                {
                    result[r, c] = nums[c];
                }
            }
        }

        return result;
    }

    private static List<double> ParseNumbers(string s)
    {
        var result = new List<double>();
        var sb = new System.Text.StringBuilder();
        foreach (char ch in s)
        {
            if (char.IsWhiteSpace(ch) || ch == '(' || ch == ')' || ch == '[' || ch == ']' || ch == ',')
            {
                if (sb.Length > 0)
                {
                    if (double.TryParse(sb.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out double v))
                    {
                        result.Add(v);
                    }

                    sb.Clear();
                }
            }
            else
            {
                sb.Append(ch);
            }
        }

        if (sb.Length > 0 && double.TryParse(sb.ToString(), NumberStyles.Float, CultureInfo.InvariantCulture, out double last))
        {
            result.Add(last);
        }

        return result;
    }
}
